ALTER TABLE users ADD COLUMN public_id TEXT;
ALTER TABLE users ADD COLUMN google_id TEXT;
ALTER TABLE users ADD COLUMN facebook_id TEXT;
ALTER TABLE users ADD COLUMN phone_number TEXT;
ALTER TABLE users ADD COLUMN bio TEXT;
ALTER TABLE users ADD COLUMN city TEXT;
ALTER TABLE users ADD COLUMN region TEXT;
ALTER TABLE users ADD COLUMN country TEXT;
ALTER TABLE users ADD COLUMN target_exam TEXT;
ALTER TABLE users ADD COLUMN target_exam_date TEXT;
ALTER TABLE users ADD COLUMN theme_preference TEXT;
ALTER TABLE users ADD COLUMN font_size_preference TEXT;
ALTER TABLE users ADD COLUMN wallet_balance REAL DEFAULT 0;
ALTER TABLE users ADD COLUMN wallet_address TEXT;
ALTER TABLE users ADD COLUMN premium_expiry TEXT;
ALTER TABLE users ADD COLUMN premium_start_date TEXT;
ALTER TABLE users ADD COLUMN streak_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN last_claim_date TEXT;
ALTER TABLE users ADD COLUMN rank_level TEXT;
ALTER TABLE users ADD COLUMN settings_friends_online INTEGER;
ALTER TABLE users ADD COLUMN settings_streak_reminder INTEGER;
ALTER TABLE users ADD COLUMN settings_new_message INTEGER;
ALTER TABLE users ADD COLUMN notify_friend_request INTEGER;
ALTER TABLE users ADD COLUMN notify_study_group INTEGER;
ALTER TABLE users ADD COLUMN notify_news_update INTEGER;
ALTER TABLE users ADD COLUMN allow_friend_request INTEGER;
ALTER TABLE users ADD COLUMN is_public_stats INTEGER;
ALTER TABLE users ADD COLUMN is_online_visible INTEGER;
ALTER TABLE users ADD COLUMN admin_permissions TEXT;
ALTER TABLE users ADD COLUMN business_name TEXT;
ALTER TABLE users ADD COLUMN business_info TEXT;
ALTER TABLE users ADD COLUMN ip_address TEXT;
ALTER TABLE users ADD COLUMN mistake_history TEXT;
ALTER TABLE users ADD COLUMN reset_password_token TEXT;
ALTER TABLE users ADD COLUMN reset_password_expires TEXT;
ALTER TABLE users ADD COLUMN last_announcement_at TEXT;
ALTER TABLE users ADD COLUMN tax_id TEXT;
ALTER TABLE users ADD COLUMN xp_points INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN extra_json TEXT;

CREATE INDEX IF NOT EXISTS idx_users_public_id ON users(public_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
